CC = g++

CFLAGS = -g

INCLUDE =

LIBS = 

# enter filename without extension
FILENAME = main

all: $(FILENAME).cpp
	@$(CC) $(CFLAGS) $(INCLUDE) $(FILENAME).cpp -o $(FILENAME) $(LIBS)

run:
	@./$(FILENAME)	

clean:
	rm ./$(FILENAME) 

